In [ ]:
#importing libraries
import numpy as np
import pandas as pd

In [ ]:
#loading the dataset and displaying the first 5 rows
df = pd.read_csv(r'C:\Users\HP\Downloads\IMDB Dataset.csv\IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
#checking the number of rows and columns in the dataset
#checking for missing values in the dataset
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

review       0
sentiment    0
dtype: int64

In [ ]:
#converting all the reviews to lowercase
df['review'] = df['review'].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [ ]:
#removing html tags from the reviews
import re
def remove_html(text):
    clean = re.sub(r'<.*?>', '', text)
    return clean
df['review'] = df['review'].apply(remove_html)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [ ]:
#removing urls from the reviews
def remove_urls(text):
    clean = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    return clean
df['review'] = df['review'].apply(remove_urls)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [ ]:
#removing numbers from the reviews
def remove_numbers(text):
    clean = re.sub(r'\d+', '', text)
    return clean
df['review'] = df['review'].apply(remove_numbers)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [ ]:
#removing punctuation from the reviews
import string
def remove_punctuation(text):
    clean = text.translate(str.maketrans('', '', string.punctuation))
    return clean
df['review'] = df['review'].apply(remove_punctuation)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [ ]:
#removing extra whitespace from the reviews
def remove_whitespace(text):
    clean = text.strip()
    return clean
df['review'] = df['review'].apply(remove_whitespace)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [ ]:
#impoting nltk library and downloading the necessary resources for tokenization
import nltk
from nltk.tokenize import word_tokenize

In [ ]:
#downloading the necessary resources for tokenization
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
#tokenizing the reviews - word tokenization
def tokenize_text(text):
    return word_tokenize(text)
df['review'] = df['review'].apply(tokenize_text)
df.head()

                                              review sentiment
0  [one, of, the, other, reviewers, has, mentione...  positive
1  [a, wonderful, little, production, the, filmin...  positive
2  [i, thought, this, was, a, wonderful, way, to,...  positive
3  [basically, theres, a, family, where, a, littl...  negative
4  [petter, matteis, love, in, the, time, of, mon...  positive

In [ ]:
#importing stop words from nltk and creating a set of stop words
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
#removing negations from the stop words list as this might affect the sentiment analysis
negations = {"not", "no", "never", "nor", "neither", "n't", "cannot", "can't", "don't", "doesn't", "didn't", "won't", "wouldn't", "shouldn't", "isn't", "aren't", "wasn't", "weren't"}
stop_words = stop_words - negations

In [ ]:
#function to remove stop words from the reviews
def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]
df['review'] = df['review'].apply(remove_stopwords)
df.head()

                                              review sentiment
0  [one, reviewers, mentioned, watching, oz, epis...  positive
1  [wonderful, little, production, filming, techn...  positive
2  [thought, wonderful, way, spend, time, hot, su...  positive
3  [basically, theres, family, little, boy, jake,...  negative
4  [petter, matteis, love, time, money, visually,...  positive

In [ ]:
#stemming the reviews using Porter Stemmer
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
def stem_tokens(tokens):
    return [stemmer.stem(word) for word in tokens]  
df['review'] = df['review'].apply(stem_tokens)
df.head()

                                              review sentiment
0  [one, review, mention, watch, oz, episod, youl...  positive
1  [wonder, littl, product, film, techniqu, unass...  positive
2  [thought, wonder, way, spend, time, hot, summe...  positive
3  [basic, there, famili, littl, boy, jake, think...  negative
4  [petter, mattei, love, time, money, visual, st...  positive

In [ ]:
#importing WordNetLemmatizer and downloading the necessary resources for lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
#lemmatizing the reviews
def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]
df['review'] = df['review'].apply(lemmatize_tokens)
df.head()

                                              review sentiment
0  [one, review, mention, watch, oz, episod, youl...  positive
1  [wonder, littl, product, film, techniqu, unass...  positive
2  [thought, wonder, way, spend, time, hot, summe...  positive
3  [basic, there, famili, littl, boy, jake, think...  negative
4  [petter, mattei, love, time, money, visual, st...  positive

In [ ]:

#joining the tokens back into a single string for each review
df['clean_review'] = df['review'].apply(lambda words: ' '.join(words))
df[['clean_review','sentiment']].head()

                                        clean_review sentiment
0  one review mention watch oz episod youll hook ...  positive
1  wonder littl product film techniqu unassum old...  positive
2  thought wonder way spend time hot summer weeke...  positive
3  basic there famili littl boy jake think there ...  negative
4  petter mattei love time money visual stun film...  positive